---
# defaults file for tomcat-ansible-role

tomcat_state: present

tomcat_version: 8.5.53
tomcat_major_version: "{{ tomcat_version.split('.')[0] }}"

tomcat_install_java: True
tomcat_java_version: 1.8
tomcat_java_home: /usr/lib/jvm/jre

tomcat_java_packages_EL:
 - {package: "java-{{ tomcat_java_version }}{% if '1.' in tomcat_java_version|string %}.0{% endif %}-openjdk"}

tomcat_downloadURL: https://archive.apache.org/dist/tomcat

tomcat_user: tomcat
tomcat_group: tomcat

tomcat_install_path: /opt
tomcat_service_name: tomcat
tomcat_jvm_memory_percentage_xms: 15
tomcat_jvm_memory_percentage_xmx: 55

tomcat_permissions_production: False
tomcat_webapps_auto_deployment: True
tomcat_permissions_ensure_on_every_run: True

tomcat_allow_manager_access_only_from_localhost: False
tomcat_allow_host_manager_access_only_from_localhost: False

tomcat_debug_mode: False

tomcat_listen_address: 0.0.0.0
tomcat_port_shutdown: 8005
tomcat_port_connector: 8080
tomcat_port_redirect: 8443
tomcat_port_ajp: 8009
tomcat_port_debug: 8000

tomcat_service_enabled_on_startup: True

tomcat_users: []

tomcat_user_roles: []

tomcat_temp_download_path: /tmp/ansibletomcattempdir

# Uninstall default parameters
tomcat_uninstall_create_backup: True

tomcat_uninstall_remove_user: True
tomcat_uninstall_remove_group: True
tomcat_uninstall_remove_java: False

tomcat_uninstall_remove_all: False

tomcat_java_opts: "-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom"
tomcat_catalina_opts_extra: ""
