---
# tasks file for tomcat-ansible-role

- name: Install Java
  yum:
    name: "{{ item.package }}"
    state: present
  with_items: "{{ tomcat_java_packages_EL }}"
  when: tomcat_install_java

- name: Create group {{ tomcat_group }}
  group:
    name: "{{ tomcat_group }}"
    gid: "{{ tomcat_group_gid | default(omit) }}"
    state: present

- name: Create user {{ tomcat_user }}
  user:
    name: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    uid: "{{ tomcat_user_uid | default(omit) }}"
    system: "{{ tomcat_user_system | default(omit) }}"
    state: present

- name: Check if tomcat tarball is already downloaded
  stat:
    path: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
  register: _tomcat_tarball

- name: Download apache-tomcat-{{ tomcat_version }}.tar.gz
  get_url:
    url: "{{ tomcat_downloadURL }}/tomcat-{{ tomcat_major_version }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
    timeout: 120
  when: not _tomcat_tarball.stat.exists

- name: Unarchive apache-tomcat-{{ tomcat_version }}.tar.gz at {{ tomcat_install_path }}
  unarchive:
    src: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_install_path }}"
    remote_src: True
    owner: "{% if tomcat_permissions_production %}root{% else %}{{ tomcat_user }}{% endif %}"
    group: "{{ tomcat_group }}"
    creates: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}"
  register: tomcat_installed
