---
# tasks file for tomcat-ansible-role

- name: Set root directory owner/group for production installation
  file:
    path: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}"
    owner: root
    group: "{{ tomcat_group }}"

- name: Set recursively directories owner/group for production installation
  file:
    path: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}/{{ item }}"
    owner: root
    group: "{{ tomcat_group }}"
    recurse: yes
  with_items:
    - bin
    - conf
    - lib

- name: Set recursively directories owner/group for production installation
  file:
    path: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}/{{ item }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    recurse: yes
  with_items:
    - logs
    - temp
    - work

- name: Set recursively webapps directory owner/group for production installation
  file:
    path: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}/webapps"
    owner: "{% if tomcat_webapps_auto_deployment %}{{ tomcat_user }}{% else %}root{% endif %}"
    group: "{{ tomcat_group }}"
    recurse: yes

- name: Find all subfolders in the tomcat install folder
  find:
    paths: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}"
    file_type: directory
    recurse: true
  register: find_result_folders

- name: Set directories permissions for production installation
  file:
    path: "{{ item.path }}"
    mode: '0750'
  loop: "{{ find_result_folders.files }}"

- name: Find all regular files (not folders) in the tomcat install folder
  find:
    paths: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}"
    file_type: file
    recurse: true
    excludes: '*.sh'  # don't change permissions for shell scripts
  register: find_result_files

- name: Set files permissions for production installation
  file:
    path: "{{ item.path }}"
    mode: '0640'
  loop: "{{ find_result_files.files }}"
