---
# tasks file for tomcat-ansible-role

- name: Set owner and group for non-production installation
  file:
    path: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    recurse: yes

- name: Find all subfolders in the tomcat install folder
  find:
    paths: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}"
    file_type: directory
  register: find_result_folders

- name: Set directories permissions for non-production installation
  file:
    path: "{{ item.path }}"
    mode: '0755'
  loop: "{{ find_result_folders.files }}"

- name: Find all regular files (not folders) in the tomcat install folder
  find:
    paths: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}"
    file_type: file
  register: find_result_files

- name: Set files permissions for non-production installation
  file:
    path: "{{ item.path }}"
    mode: '0664'
  loop: "{{ find_result_files.files }}"
